version: '3.2'
services:
  node:
    build:
      context: .
      dockerfile: ./node/Dockerfile
      args:
        USER_NAME: vscode
        GROUP_NAME: vscode
        USER_UID: 1000
        USER_GID: 1000
    ports:
      - "8001:8000"
    env_file: devcontainer.env
    environment:
      - TZ=JST-9
    volumes:
      - ..:/home/vscode/develop_container
      - ../../../notes:/home/vscode/notes:cached
    command: /bin/sh -c "while sleep 1000; do :; done"